var db = require("../../db");
var mongoose = require("mongoose");
const aggregatePaginate = require("mongoose-aggregate-paginate-v2");
Schema = mongoose.Schema;

var employeeDetailsSchema = Schema(
  {
    employee_id: {
      type: Schema.Types.ObjectId,
      required: true,
      ref: "employees",
    },
    corporate_id: { type: String, required: true },
    emp_id: { type: String },
    emp_address: {
      resident_no: { type: String },
      residential_name: { type: String },
      road: { type: String },
      locality: { type: String },
      city: { type: String },
      district: { type: String },
      state: { type: String },
      pincode: { type: String },
      country: { type: String },
      address_proof: {
        type: String,
        // enum: ["aadhaar", "pan"],
        // default: "aadhaar",
      },
      emp_address_proof: { type: String },
      diff_current_add: { type: String, enum: ["no", "yes"], default: "no" },
    },

    emp_curr_address: {
      resident_no: { type: String },
      residential_name: { type: String },
      road: { type: String },
      locality: { type: String },
      city: { type: String },
      district: { type: String },
      state: { type: String },
      pincode: { type: String },
      country: { type: String },
    },
    bank_details: {
      bank_name: { type: String },
      branch_name: { type: String },
      branch_address: { type: String },
      branch_pin: { type: String },
      account_no: { type: String },
      account_type: { type: String },
      ifsc_code: { type: String },
      micr_no: { type: String },
      cancel_cheque: { type: String },
    },
    pf_esic_details: {
      pre_er_pf: {
        type: String,
        enum: ["yes", "no"],
        default: "no",
      },
      pre_er_details: {
        er_name: { type: String },
        last_drawn_gross: { type: String },
        contact_no: { type: String },
        reporting_to: { type: String },
        exit_date: { type: String },
        last_designation: { type: String },
      },
      pre_er_epfo_details: {
        uan_no: { type: String },
        last_member_id: { type: String },
        last_ro: { type: String },
      },
      pre_er_esic_details: {
        esic_no: { type: String },
        ip_dispensary: { type: String },
        family_dispensary: { type: String },
      },
      curr_er_epfo_details: {
        uan_no: { type: String },
        last_member_id: { type: String },
        last_ro: { type: String },
        membership_date: { type: String },
      },
      curr_er_esic_details: {
        esic_no: { type: String },
        ip_dispensary: { type: String },
        family_dispensary: { type: String },
        membership_date: { type: String },
      },
      esic_family_details: [
        {
          fm_name: { type: String },
          fm_dob: { type: String },
          fm_relation: { type: String },
          sex: { type: String },
          residing_with_if: {
            type: String,
            enum: ["yes", "no"],
            default: "yes",
          },
        },
      ],
      pf_nominee_details: [
        {
          aadhar_no: { type: String },
          dob: { type: String },
          name: { type: String },
          sex: { type: String },
          fm_relation: { type: String },
          address: { type: String },
          profile_pic: { type: String },
        },
      ],
    },
    employment_hr_details: {
      department: { type: Schema.Types.Mixed },
      designation: { type: Schema.Types.Mixed },
      branch: { type: Schema.Types.Mixed },
      date_of_join: { type: String },
      hod: { type: Schema.Types.Mixed },
      client: { type: Schema.Types.Mixed },
      emp_type: { type: String },
      pension_applicable: { type: String },
      gross_salary: { type: Number },
      emp_role: { type: String },
      emp_self_service: { type: String },
      esic_covered: { type: String },
      esic_gross: { type: Number },
      gross_earning: { type: Number },

      // emp_id    : {type: String},
      // password    : {type: String},
      package_id: { type: Schema.Types.Mixed },
      salary_temp: { type: Schema.Types.Mixed },
      emp_role_data: {},
      // annual_benefit    : {type: String},
      // pf_applicable    : {type: String},
      location_id: { type: Schema.Types.Mixed, required: false},
    },
    employment_details: {
      new_pf_no: { type: String },
      uan_no: { type: String },
      esic_no: { type: String },
      esic_dispensary: { type: String },
      pf_no_per_dep_file: { type: String },
      pf_membership_date: { type: String },
      esic_membership_date: { type: String },
    },
    contract: [
      {
        description: { type: String },
        comments: { type: String },
        start_date: { type: String },
        end_date: { type: String },
        contract_file_image: { type: String },
      },
    ],
    annual_earnings: [
      {
        earning_head: { type: String },
        earning_category: { type: String },
        earning_amount: { type: String },
        contract_file_image: { type: String },
      },
    ],
    training: [
      {
        training_type: { type: String },
        description: { type: String },
        comments: { type: String },
        training_file_image: { type: String },
      },
    ],
    annual_earnings: [
      {
        earning_head_id: { type: String },
        earning_category: { type: String },
        earning_amount: { type: String },
        contract_file_image: { type: String },
      },
    ],
    employment_disciplinary_details: [
      {
        disciplinary_type: { type: String },
        description: { type: String },
        comments: { type: String },
        disciplinary_file_image: { type: String },
      },
    ],
    accident: [
      {
        accident_type: { type: String },
        description: { type: String },
        comments: { type: String },
        date: { type: String },
        accident_file_image: { type: String },
      },
    ],
    extra_curricular: [
      {
        extra_curricular_type: { type: String },
        description: { type: String },
        comments: { type: String },
        date: { type: String },
        extra_curricular_file_image: { type: String },
      },
    ],
    education: [
      {
        institute: { type: String },
        university: { type: String },
        stream: { type: String },
        level: { type: String },
        specialisation: { type: String },
        completion: { type: String },
        education_file_image: { type: String },
      },
    ],
    assets: [
      {
        asset_details: { type: String },
        asset_no: { type: String },
        asset_value: { type: String },
        asset_qty: { type: String },
        asset_issue_date: { type: String },
        asset_receive_date: { type: String },
        asset_receive_by: { type: String },
      },
    ],
    full_and_final: {
      do_resignation: { type: Date, default: null },
      emp_notice_period: { type: Number },
      er_notice_period: { type: Number },
      last_working_date: { type: String },
      reason_code: { type: Number },
      exit_date: { type: Date },
      is_final_settlement: Boolean,
      is_net_pay: Boolean,
      is_employee_pf: Boolean,
      is_employer_pf: Boolean,
      is_employee_esic: Boolean,
      is_employer_esic: Boolean,
      is_ptax: Boolean,
      is_leave_encashment: Boolean,
      is_accumulated_bonus: Boolean,
      is_outstanding_incentive: Boolean,
      is_less_tds: Boolean,
      is_less_outstanding_advance: Boolean,
      is_gratuity: Boolean,
      footer_text: String,
      is_notice_pay:Boolean,
      payble_days:Number,
      extra_fields: [
        {
          label: String,
          value: String,
        },
      ],
      // extra_field: [
      //   {
      //     f_lable: { type: String },
      //     f_value: { type: String },
      //   },
      // ],
    },
    employment_other_details: {
      description: { type: String },
      comments: { type: String },
      date: { type: String },
    },
    template_data: {
      salary_temp_data: { type: Schema.Types.Mixed },
      attendance_temp_data: { type: Schema.Types.Mixed },
      bonus_temp_data: { type: Schema.Types.Mixed },
      incentive_temp_data: { type: Schema.Types.Mixed },
      overtime_temp_data: { type: Schema.Types.Mixed },
      ptax_temp_data: { type: Schema.Types.Mixed },
      leave_temp_data: { type: Schema.Types.Mixed },
      lwf_temp_data: { type: Schema.Types.Mixed },
      tds_temp_data: { type: Schema.Types.Mixed },
      payslip_temp_data: { type: Schema.Types.Mixed },
      bonus_slip_temp_data: { type: Schema.Types.Mixed },
      arrear_slip_temp_data: { type: Schema.Types.Mixed },
    },
    salary_breakups: [{ type: Schema.Types.Mixed }],
    family_member: [
      {
        name: { type: String },
        dob: { type: String },
        relation: { type: String },
        dependent: { type: String },
        nominee: { type: String },
        aadhaar_no: { type: String },
        family_mem_aadhar_image: { type: String },
      },
    ],
    leave_balance: {
      pvl: { type: String, default: "0" },
      erl: { type: String, default: "0" },
      pdl: { type: String, default: "0" },
      skl: { type: String, default: "0" },
      csl: { type: String, default: "0" },
      mdl: { type: String, default: "0" },
      mtl: { type: String, default: "0" },
      ptl: { type: String, default: "0" },
      anl: { type: String, default: "0" },
      awp: { type: String, default: "0" },
      uwp: { type: String, default: "0" },
      le1: { type: String, default: "0" },
      le2: { type: String, default: "0" },
      lp1: { type: String, default: "0" },
      lp2: { type: String, default: "0" },
    },
    leave_balance_counter: [
      {
        leave_temp_head_id: { type: Schema.Types.ObjectId },
        leave_type_name: { type: String },
        abbreviation: { type: String },
        available: { type: String },
        consumed: { type: String },
        total_balance: { type: String },
        tenure: { type: String },
        quota: { type: String },
        carryover: { type: String },
        encash: { type: String },
        extinguish: { type: String },
      },
    ],
    kpi_and_appraisal: {
      self_assignee: {
        assignee_id: Schema.Types.ObjectId,
        assign_value: Number,
      },
      lvl_1_assignee: {
        assignee_id: Schema.Types.ObjectId,
        assign_value: Number,
      },
      lvl_2_assignee: {
        assignee_id: Schema.Types.ObjectId,
        assign_value: Number,
      },
      rating_heads: [
        {
          head_name: String,
          head_value: Number,
        },
      ],
      status: {
        type: String,
        enum: ["pending", "active", "inactive", "completed"],
        default: "pending",
      },
    },
    created_at: { type: Date },
    updated_at: { type: Date, default: Date.now() },
  },
  { strict: false }
);
employeeDetailsSchema.plugin(aggregatePaginate);
var employeeDetails = db.model("employee_details", employeeDetailsSchema);
module.exports = employeeDetails;
