export const _rolesManagmentMaster: any[] = [
  {
    name: 'Government Rules',
    slug: 'government_rules',
    status: 'active',
    package_slug: 'government_rules',
    modules: [
      {
        package_module_name: '',
        package_module_slug: 'gov_pf_rule',
        module_name: 'PF Rules',
        module_slug: 'pf_rules',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: 'gov_esic_rule',
        module_name: 'ESI Rules',
        module_slug: 'esi_rules',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: 'gov_bonus_rule',
        module_name: 'Bonus Rules',
        module_slug: 'bonus_rules',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: 'gov_gratuity_rule',
        module_name: 'Gratuity',
        module_slug: 'gratuity',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: 'gov_ptax_rule',
        module_name: 'Income Tax Slabs',
        module_slug: 'income_tax_slabs',
        access: ['view', 'add', 'edit', 'delete'],
      },
    ],
  },
  {
    name: 'Company Rules 1',
    slug: 'company_rules_1',
    status: 'active',
    package_slug: '',
    modules: [
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Policy Package',
        module_slug: 'policy_package',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Salary Template',
        module_slug: 'salary_template',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Attendance Policy ',
        module_slug: 'attendance_policy_',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Leave Policy',
        module_slug: 'leave_policy',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Incentive Policy',
        module_slug: 'incentive_policy',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Bonus Policy',
        module_slug: 'bonus_policy',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Overtime Policy',
        module_slug: 'overtime_policy',
        access: ['view', 'add', 'edit', 'delete'],
      },
    ],
  },
  {
    name: 'Company Rules 2',
    slug: 'company_rules_2',
    status: 'active',
    package_slug: '',
    modules: [
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'P Tax Rules',
        module_slug: 'p_tax_rules',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'LWF Rules',
        module_slug: 'lwf_rules',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'TDS Rules',
        module_slug: 'tds_rules',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: 'tds_template',
        module_name: 'TDS Template',
        module_slug: 'tds_template',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: 'pay_slip_template',
        module_name: 'Pay Slip Template',
        module_slug: 'pay_slip_template',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: 'bonus_slip_template',
        module_name: 'Bonus Slip Template',
        module_slug: 'bonus_slip_template',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: 'arrear_slip_template',
        module_name: 'Arrear Slip Template',
        module_slug: 'arrear_slip_template',
        access: ['view', 'add', 'edit', 'delete'],
      },
    ],
  },
  {
    name: 'Master',
    slug: 'master',
    status: 'active',
    package_slug: '',
    modules: [
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Department',
        module_slug: 'department',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Designation',
        module_slug: 'designation',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Branch',
        module_slug: 'branch',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Client',
        module_slug: 'client',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Bank Payment',
        module_slug: 'bank_payment',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Letter Writer',
        module_slug: 'letter_writer',
        access: ['view', 'add', 'edit', 'delete'],
      },
    ],
  },
  {
    name: 'Sub Admin',
    slug: 'sub_admin',
    status: 'active',
    package_slug: '',
    modules: [
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Staff Management',
        module_slug: 'staff_management',
        access: ['view', 'add', 'edit', 'delete'],
      },
      {
        package_module_name: 'Role & Rights',
        package_module_slug: 'role_management',
        module_name: 'Role & Rights',
        module_slug: 'role_&_rights',
        access: ['view', 'add', 'edit', 'delete'],
      },
    ],
  },
  {
    name: 'Company Profile',
    slug: 'company_profile',
    status: 'active',
    package_slug: '',
    modules: [
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Company Profile',
        module_slug: 'company_profile',
        access: ['view', 'add', 'edit', 'delete'],
      },
    ],
  },
  {
    name: 'Employee',
    slug: 'employee',
    package_slug: 'employee',
    status: 'active',
    modules: [
      {
        package_module_name: 'Employee Master Data',
        package_module_slug: 'listing_add_approve',
        module_name: 'Employee Master Data',
        module_slug: 'employee_master_data',
        access: ['view', 'add', 'edit', 'approve', 'invitation'],
      },
      {
        package_module_name: 'Employee Exit',
        package_module_slug: 'employee_exit',
        module_name: 'Employee Exit',
        module_slug: 'employee_exit',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Full & Final',
        package_module_slug: 'fullnfinal',
        module_name: 'Full & Final',
        module_slug: 'full_&_final',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Asset Management',
        package_module_slug: 'asset_management',
        module_name: 'Asset Management',
        module_slug: 'asset_management',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Annual Component',
        package_module_slug: 'annual_component',
        module_name: 'Annual Component',
        module_slug: 'annual_component',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Letter Writer',
        package_module_slug: 'letter_writer',
        module_name: 'Letter Writer',
        module_slug: 'letter_writer',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Bulk Joining',
        package_module_slug: 'bulk_upload',
        module_name: 'Bulk Joining',
        module_slug: 'bulk_joining',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Employee Master Report',
        package_module_slug: 'listing_add_approve',
        module_name: 'Employee Master Report',
        module_slug: 'employee_master_report',
        access: ['view', 'add', 'edit'],
      },
    ],
  },
  {
    name: 'Attendance',
    slug: 'attendance',
    package_slug: 'attendance',
    status: 'active',
    modules: [
      {
        package_module_name: 'Upload Attendance',
        package_module_slug: 'attendance_upload',
        module_name: 'Upload Attendance',
        module_slug: 'upload_attendance',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Attendance Funnel',
        package_module_slug: 'attendance_funnel',
        module_name: 'Attendance Funnel',
        module_slug: 'attendance_funnel',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Edit Attendance',
        package_module_slug: 'attendance_edit',
        module_name: 'Edit Attendance',
        module_slug: 'edit_attendance',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Attendance Report',
        package_module_slug: 'attendance_report',
        module_name: 'Attendance Report',
        module_slug: 'attendance_report',
        access: ['view', 'edit'],
      },
    ],
  },
  {
    name: 'Incentive',
    slug: 'incentive',
    package_slug: 'incentive',
    status: 'active',
    modules: [
      {
        package_module_name: 'Add/Apply Incentive',
        package_module_slug: 'add_incentive',
        module_name: 'Add/Apply Incentive',
        module_slug: 'add_apply_incentive',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Incentive Report',
        package_module_slug: 'incentive_report',
        module_name: 'Incentive Report',
        module_slug: 'incentive_report',
        access: ['view', 'edit'],
      },
      {
        package_module_name: 'Payment Instructions',
        package_module_slug: 'payment_instruction',
        module_name: 'Payment Instructions',
        module_slug: 'payment_instructions',
        access: ['view', 'add', 'edit'],
      },
    ],
  },
  {
    name: 'Salary',
    slug: 'salary',
    status: 'active',
    package_slug: 'salary',
    modules: [
      {
        package_module_name: 'Run Payroll',
        package_module_slug: 'run_payroll',
        module_name: 'Run Payroll',
        module_slug: 'run_payroll',
        access: ['view', 'Run', 'edit'],
      },
      {
        package_module_name: 'Hold Salary',
        package_module_slug: 'hold_salary',
        module_name: 'Hold Salary',
        module_slug: 'hold_salary',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Supli Salary',
        package_module_slug: 'supli_salary',
        module_name: 'Supli Salary',
        module_slug: 'supli_salary',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Payment Instructions',
        package_module_slug: 'payment_instructions',
        module_name: 'Payment Instructions',
        module_slug: 'payment_instructions',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Pay Slip',
        package_module_slug: 'payslip',
        module_name: 'Pay Slip',
        module_slug: 'pay_slip',
        access: ['view', 'generate', 'edit'],
      },
      {
        package_module_name: 'Salary Report',
        package_module_slug: 'salary_earning_report',
        module_name: 'Salary Report',
        module_slug: 'salary_report',
        access: ['view', 'edit'],
      },
    ],
  },
  {
    name: 'Bonus',
    slug: 'bonus',
    package_slug: 'bonus',
    status: 'active',
    modules: [
      {
        package_module_name: 'Apply Bonus',
        package_module_slug: 'bonus_applyed',
        module_name: 'Apply Bonus',
        module_slug: 'apply_bonus',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Bonus Report',
        package_module_slug: 'bonus_report',
        module_name: 'Bonus Report',
        module_slug: 'bonus_report',
        access: ['view'],
      },
      {
        package_module_name: 'Payment Instruction',
        package_module_slug: 'payment_instruction',
        module_name: 'Payment Instructions',
        module_slug: 'payment_instructions',
        access: ['view', 'add', 'edit'],
      },
    ],
  },
  {
    name: 'Revision Management',
    slug: 'revision_management',
    package_slug: 'salary_revision',
    status: 'active',
    modules: [
      {
        package_module_name: 'Apply Revision',
        package_module_slug: 'apply_revision',
        module_name: 'Apply Revision',
        module_slug: 'apply_revision',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Revision Report',
        package_module_slug: 'revision_report',
        module_name: 'Revision Report',
        module_slug: 'revision_report',
        access: ['view', 'edit'],
      },
      {
        package_module_name: 'Run Arrear',
        package_module_slug: 'run_arrear',
        module_name: 'Run Arrear',
        module_slug: 'run_arrear',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Arrear Report',
        package_module_slug: 'arrear_report',
        module_name: 'Arrear Report',
        module_slug: 'arrear_report',
        access: ['view', 'edit'],
      },
      {
        package_module_name: 'Payment Instruction',
        package_module_slug: 'payment_instruction',
        module_name: 'Payment Instructions',
        module_slug: 'payment_instructions',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Arrear Slip',
        package_module_slug: 'arrear_slip',
        module_name: 'Arrear Slip',
        module_slug: 'arrear_slip',
        access: ['view', 'add', 'edit'],
      },
    ],
  },
  {
    name: 'Advance',
    slug: 'advance',
    status: 'active',
    package_slug: 'advance_management',
    modules: [
      {
        package_module_name: 'Apply/Approve Advance',
        package_module_slug: 'apply_approve_advance',
        module_name: 'Apply Advance',
        module_slug: 'apply_advance',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Apply/Approve Advance',
        package_module_slug: 'apply_approve_advance',
        module_name: 'Approve Advance',
        module_slug: 'approve_advance',
        access: ['view', 'add', 'edit', 'approve'],
      },
      {
        package_module_name: 'Advance Report',
        package_module_slug: 'advance_report',
        module_name: 'Advance Report',
        module_slug: 'advance_report',
        access: ['view'],
      },
    ],
  },
  {
    name: 'Over Time',
    slug: 'over_time',
    status: 'active',
    package_slug: 'over_time',
    modules: [
      {
        package_module_name: 'OT Report',
        package_module_slug: 'overtime_report',
        module_name: 'OT Report',
        module_slug: 'ot_report',
        access: ['view'],
      },
    ],
  },
  {
    name: 'Leave',
    slug: 'leave',
    package_slug: 'leave_management',
    status: 'active',
    modules: [
      {
        package_module_name: 'Leave Ledger',
        package_module_slug: 'leave_ledger',
        module_name: 'Leave Ledger',
        module_slug: 'leave_ledger',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Leave Encashment',
        package_module_slug: 'leave_incashment',
        module_name: 'Leave Encashment',
        module_slug: 'leave_encashment',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Leave Report',
        package_module_slug: 'leave_report',
        module_name: 'Leave Report',
        module_slug: 'leave_report',
        access: ['view'],
      },
    ],
  },
  {
    name: 'TDS Management',
    slug: 'tds_management',
    package_slug: 'tds_management',
    status: 'active',
    modules: [
      {
        package_module_name: 'Apply/Approve TDS',
        package_module_slug: 'apply_approve_tds',
        module_name: 'Apply TDS Decl',
        module_slug: 'apply_tds_decl',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Apply/Approve TDS',
        package_module_slug: 'apply_approve_tds',
        module_name: 'Approve TDS Decl',
        module_slug: 'approve_tds_decl',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'TDS Report',
        package_module_slug: 'tds_report',
        module_name: 'TDS Report',
        module_slug: 'tds_report',
        access: ['view', 'add', 'edit'],
      },
    ],
  },
  {
    name: 'Shift Management',
    slug: 'shift_management',
    package_slug: 'shift_management',
    status: 'active',
    modules: [
      {
        package_module_name: 'Define Shift',
        package_module_slug: 'define_shift_allowance_batch',
        module_name: 'Define Shift',
        module_slug: 'define_shift',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Define Shift Allowance',
        package_module_slug: 'define_shift_allowance_batch',
        module_name: 'Define Shift Allowance',
        module_slug: 'define_shift_allowance',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Allocate Shift',
        package_module_slug: 'define_shift_allowance_batch',
        module_name: 'Allocate Shift',
        module_slug: 'allocate_shift',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Manage Shift Batch',
        package_module_slug: 'manage_shift_rate',
        module_name: 'Manage Shift Batch',
        module_slug: 'manage_shift_batch',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Shift Report',
        package_module_slug: 'shift_report',
        module_name: 'Shift Report',
        module_slug: 'shift_report',
        access: ['view'],
      },
      {
        package_module_name: 'Shift Duty Report',
        package_module_slug: 'shift_duty_report',
        module_name: 'Shift Duty Report',
        module_slug: 'shift_duty_report',
        access: ['view'],
      },
      {
        package_module_name: 'Shift Earning Report',
        package_module_slug: 'shift_earning_report',
        module_name: 'Shift Earning Report',
        module_slug: 'shift_earning_report',
        access: ['view'],
      },
    ],
  },
  {
    name: 'Layoff Management',
    slug: 'layoff_management',
    package_slug: 'layoff_management',
    status: 'active',
    modules: [
      {
        package_module_name: 'Apply Lay-off',
        package_module_slug: 'apply_layoff',
        module_name: 'Apply Lay-off',
        module_slug: 'apply_lay-off',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'Lay-off Report',
        package_module_slug: 'layoff_report',
        module_name: 'Lay-off Report',
        module_slug: 'lay-off_report',
        access: ['view'],
      },
    ],
  },
  {
    name: 'Payment Instructions',
    slug: 'payment_instructions',
    status: 'active',
    package_slug: '',
    modules: [
      {
        package_module_name: '',
        package_module_slug: '',
        module_name: 'Instructions Listing',
        module_slug: 'instructions_listing',
        access: ['view', 'download', 'confirm', 'delete'],
      },
    ],
  },
  {
    name: 'Compliance',
    slug: 'compliance',
    package_slug: 'compliance',
    status: 'active',
    modules: [
      {
        package_module_name: 'Compliance Listing',
        package_module_slug: 'compliance_listing',
        module_name: 'Compliance Listing',
        module_slug: 'compliance_listing',
        access: ['view', 'generate', 'edit', 'delete'],
      },
      {
        package_module_name: 'Challan Data',
        package_module_slug: 'challan_data_listing',
        module_name: 'Challan Data',
        module_slug: 'challan_data',
        access: ['view', 'download', 'confirm', 'delete'],
      },
      {
        package_module_name: 'PF Report',
        package_module_slug: 'pf_report',
        module_name: 'PF Report',
        module_slug: 'pf_report',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'ESI Report',
        package_module_slug: 'esi_report',
        module_name: 'ESI Report',
        module_slug: 'esi_report',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'P Tax Report',
        package_module_slug: 'p_tax_report',
        module_name: 'P Tax Report',
        module_slug: 'p_tax_report',
        access: ['view', 'add', 'edit'],
      },
      {
        package_module_name: 'LWF Report',
        package_module_slug: 'lwf_report',
        module_name: 'LWF Report',
        module_slug: 'lwf_report',
        access: ['view', 'add', 'edit'],
      },
    ],
  },
  {
    name: 'Government Returns',
    slug: 'government_returns',
    package_slug: 'government_returns',
    status: 'active',
    modules: [],
  },
  {
    name: 'Appraisal',
    slug: 'appraisal',
    package_slug: 'appraisal',
    status: 'active',
    modules: [],
  },
  {
    name: 'Audit',
    slug: 'audit',
    package_slug: 'audit',
    status: 'active',
    modules: [],
  },
  {
    name: 'Library',
    slug: 'library',
    package_slug: 'library',
    status: 'active',
    modules: [],
  },
];
